name: Publish container

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Deploy Azure Static Web App"
    types:
      - completed

concurrency: 
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publishContainer:
    environment:
      name: mitchfen-xyz-container
      url: https://mitchfen-xyz-container.azurewebsites.net/
    runs-on: ubuntu-latest
    env:
      CUSTOM_DOMAIN_VERIFICATION_ID: ${{ secrets.CUSTOM_DOMAIN_VERIFICATION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Az login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Docker login
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAGES_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
